[레벨3 - 성숙] 희봉 미션 제출합니다.
woowacourse/woowa-writing-1 pull request #128
Opened 2019-10-23 07:44 UTC by heebong

미래의 꿈을 이야기하는데 오히려 개발을 왜 하고싶었는지 돌아보게 되는 계기가 되었습니다. 앞으로도 흔들릴 때 이걸 읽으며 맞게 나아가고 있는지 확인할 수 있을것 같습니다. 😄

2019-10-24 10:30 UTC, yk1028 requested changes
수고하셨습니다~ 💯

2019-10-24 10:30 UTC, yk1028 commented on 레벨 3 - 성숙.md
> +  보여주기식이 아닌 사용자들이 필요로 하는 프로그램을 만들고 있었으면 한다. 기술로만 해결할 수 있는 문제들을 해결해 사람들에게 즐거움이나 편리한 서비스를 제공하는 프로그램을 만들었고, 계속해서 만들어 나가는 중이길 희망한다. 세상에 의미 있는 가치를 생성하는 프로그래머로 살아가고 있길 원한다.
`세상에 의미 있는 가치를 생성하는 프로그래머로 살아가고 있길 원한다.` -> `세상에 의미 있는 가치를 만들어내는 프로그래머로 살아가고 싶다.` 로 바꿔보는건 어떨까요?
아니면 앞에 `미래의 나는` 같은 문구가 붙어야할 것 같아요.

2019-10-24 10:30 UTC, yk1028 commented on 레벨 3 - 성숙.md
> +#### 지속적인 배움의 열정
`지속적인 배움의 열정`  -> `지속적인 배움에 대한 열정`으로 바꿔보는 건 어떨까요?
배움이 능동적인 것 같아서 약간 어색해 보여요:)

2019-10-24 10:30 UTC, yk1028 commented on 레벨 3 - 성숙.md
> +#### 즐기는 삶
👍

2019-10-24 10:58 UTC, ep1stas1s reviewed
정말 공감되네요!
희봉의 꿈 꼭 이뤄지길 응원합니다🤜🤛

2019-10-24 10:58 UTC, ep1stas1s commented on 레벨 3 - 성숙.md
> +  모두 다 좋지만 마지막은 역시 즐기면서 살았으면 좋겠다. 프로그램을 처음 시작하게 된 이유도 코드를 짜는 것이 즐거웠기 때문이다. 코딩이 아닌 다른 것이 즐거워진다면 그것으로 변경해도 괜찮다. 하지만 즐겁지 않은 상태로 계속해서 코딩을 하진 말았으면 한다. 즐겁지 않다면 순응하지 말고 즐거움을 찾아가는 과정을 가졌으면 좋겠다. **행복하게 즐기면서 살
크 공감합니다!👍

2019-10-24 10:58 UTC, ep1stas1s commented on 레벨 3 - 성숙.md
> +  보여주기식이 아닌 사용자들이 필요로 하는 프로그램을 만들고 있었으면 한다. 기술로만 해결할 수 있는 문제들을 해결해 사람들에게 즐거움이나 편리한 서비스를 제공하는 프로그램을 만들었고, 계속해서 만들어 나가는 중이길 희망한다. 세상에 의미 있는 가치를 생성하는 프로그래머로 살아가고 있길 원한다.
```suggestion
  보여주기식이 아닌 사용자들이 필요로 하는 프로그램을 만들고 있었으면 한다. 일상 생활의 문제들을 기술로 해결하면서 사람들에게 즐거움이나 편의성을 제공하는 프로그램을 꾸준히 만들기를 희망한다. 세상에 의미 있는 가치를 생성하는 프로그래머로 살아가고 있길 원한다.
```
저도 한글이 부족해서... 어떻게 해야할 진 모르겠는데 문장이 조금 어색한 것 같습니다😅

2019-10-24 14:53 UTC, hyunniiii approved these changes
안녕하세요 희봉! 깔끔한 글이어서 리뷰 할 게 없는 것 같아요! 지속적인 배움의 열정.. 개발자에게 반드시 필요한 부분 같아요. 가끔 지쳐서 아무것도 하고 싶지 않을 때도 있거든요 :( 글에서 비 개발자들에게도 쉽게 알려주는 개발자가 되고 싶다고 했는데 이 부분은 스토리텔링 하듯이 설명해주면 이해하기 좋은 것 같아요! 희봉의 뜻대로 행복하고 즐길 수 있는 삶을 응원합니다. 글 잘 읽었습니다. :)

2019-10-24 14:55 UTC, ddu0422 reviewed
안녕하세요 희봉~ 리뷰어 미르입니다 :)
좋은 글 잘 읽었습니다.
뚜렷한 목표를 가지고 계시네요. 해당 목표를 차근차근 달성해보아요 :)
간단한 피드백 남겼으니 확인해주세요~

2019-10-24 14:55 UTC, ddu0422 commented on 레벨 3 - 성숙.md
> +  이 주제를 받았을 때 어떤 식으로 풀어써야 할지 막막했다. 일기 형식으로 써볼까, 내가 만들고 싶은 프로그램들을 적어볼까 여러 가지가 있었지만 개발자로써 내가 지켰으면 하는 규칙들과 중요하게 생각하는 가치들을 적어보기로 했다. 내가 꿈꾸는 프로그래머의 삶은 아래의 조건들을 만족하는 생활이다.
`로서` 가 아닐까요?

2019-10-24 14:55 UTC, ddu0422 commented on 레벨 3 - 성숙.md
> +  모두 다 좋지만 마지막은 역시 즐기면서 살았으면 좋겠다. 프로그램을 처음 시작하게 된 이유도 코드를 짜는 것이 즐거웠기 때문이다. 코딩이 아닌 다른 것이 즐거워진다면 그것으로 변경해도 괜찮다. 하지만 즐겁지 않은 상태로 계속해서 코딩을 하진 말았으면 한다. 즐겁지 않다면 순응하지 말고 즐거움을 찾아가는 과정을 가졌으면 좋겠다. **행복하게 즐기면서 살
저도 코딩을 즐기면서 하는 삶을 살고 싶네요 :)

2019-10-24 14:55 UTC, ddu0422 commented on 레벨 3 - 성숙.md
> +  기술은 계속해서 발전한다. 그 의미는 기술로 해결할 수 있는 문제들의 범위도 점점 넓어진다는 것이다. 때문에 새로운 가치를 계속해서 만들기 위해선 변화하는 기술에 대한 공부가 함께 수반되어야 한다. 끊임없이 새로운 것을 학습하는 건 고통일 수도 있지만 축복일 수도 있다. 축복으로 생각하진 않더라도, 현재에 안주하지 않고 계속해서 배우고픈 열망을 가진
맞아요 ㅠㅠ 배울게 너무 많지만 열정을 가지고 해보는 거죠 !

2019-10-25 07:22 UTC, heebong commented on 레벨 3 - 성숙.md
> +  보여주기식이 아닌 사용자들이 필요로 하는 프로그램을 만들고 있었으면 한다. 기술로만 해결할 수 있는 문제들을 해결해 사람들에게 즐거움이나 편리한 서비스를 제공하는 프로그램을 만들었고, 계속해서 만들어 나가는 중이길 희망한다. 세상에 의미 있는 가치를 생성하는 프로그래머로 살아가고 있길 원한다.
변경했습니다. 피드백 감사드립니다!!

2019-10-25 07:22 UTC, heebong commented on 레벨 3 - 성숙.md
> +#### 지속적인 배움의 열정
반영했습니다. 피드백 감사드립니다!

2019-10-25 07:23 UTC, heebong commented on 레벨 3 - 성숙.md
> +  모두 다 좋지만 마지막은 역시 즐기면서 살았으면 좋겠다. 프로그램을 처음 시작하게 된 이유도 코드를 짜는 것이 즐거웠기 때문이다. 코딩이 아닌 다른 것이 즐거워진다면 그것으로 변경해도 괜찮다. 하지만 즐겁지 않은 상태로 계속해서 코딩을 하진 말았으면 한다. 즐겁지 않다면 순응하지 말고 즐거움을 찾아가는 과정을 가졌으면 좋겠다. **행복하게 즐기면서 살
즐거운게 최고죠!!! 😄

2019-10-25 07:23 UTC, heebong commented on 레벨 3 - 성숙.md
> +  보여주기식이 아닌 사용자들이 필요로 하는 프로그램을 만들고 있었으면 한다. 기술로만 해결할 수 있는 문제들을 해결해 사람들에게 즐거움이나 편리한 서비스를 제공하는 프로그램을 만들었고, 계속해서 만들어 나가는 중이길 희망한다. 세상에 의미 있는 가치를 생성하는 프로그래머로 살아가고 있길 원한다.
훨씬 매끄러워요! 반영했습니다. 피드백 감사드려요!!

2019-10-25 07:24 UTC, heebong commented on 레벨 3 - 성숙.md
> +  이 주제를 받았을 때 어떤 식으로 풀어써야 할지 막막했다. 일기 형식으로 써볼까, 내가 만들고 싶은 프로그램들을 적어볼까 여러 가지가 있었지만 개발자로써 내가 지켰으면 하는 규칙들과 중요하게 생각하는 가치들을 적어보기로 했다. 내가 꿈꾸는 프로그래머의 삶은 아래의 조건들을 만족하는 생활이다.
변경했습니다~ 피드백 감사합니다!

2019-10-25 07:24 UTC, heebong commented on 레벨 3 - 성숙.md
> +  모두 다 좋지만 마지막은 역시 즐기면서 살았으면 좋겠다. 프로그램을 처음 시작하게 된 이유도 코드를 짜는 것이 즐거웠기 때문이다. 코딩이 아닌 다른 것이 즐거워진다면 그것으로 변경해도 괜찮다. 하지만 즐겁지 않은 상태로 계속해서 코딩을 하진 말았으면 한다. 즐겁지 않다면 순응하지 말고 즐거움을 찾아가는 과정을 가졌으면 좋겠다. **행복하게 즐기면서 살
즐거운게 최고에요 👍 즐기면서 살아요!

2019-10-25 07:25 UTC, heebong commented on 레벨 3 - 성숙.md
> +  기술은 계속해서 발전한다. 그 의미는 기술로 해결할 수 있는 문제들의 범위도 점점 넓어진다는 것이다. 때문에 새로운 가치를 계속해서 만들기 위해선 변화하는 기술에 대한 공부가 함께 수반되어야 한다. 끊임없이 새로운 것을 학습하는 건 고통일 수도 있지만 축복일 수도 있다. 축복으로 생각하진 않더라도, 현재에 안주하지 않고 계속해서 배우고픈 열망을 가진
열정 가지고 달려봅시다...! 🏎

2019-10-26 04:03 UTC, ddu0422 approved these changes
안녕하세요 희봉~ 리뷰어 미르입니다.
피드백 반영 확인했습니다. 💯 💯 
코딩을 즐기는 모습이 인상적이네요 :) 
언제든지 즐길 수 있는 것으로 변경할 수 있는 자신감이 대단하네요 !!
저도 그런 자신감을 가져야겠네요 ㅎㅎ
글쓰기 하시느라 고생하셨어요~~
이만 Approve 하겠습니다.

2019-10-26 04:27 UTC, ep1stas1s approved these changes
피드백 반영 해주셔서 감사합니다^^
제 생각에 이미 소통은 충분히 잘 하시는 것 같습니다😀
피드백도 남다르고, 글도 깔끔하게 잘 쓰시네요ㅎㅎ
이번 레벨도 잘 마무리하시고, 앞으로도 좋은 결과 있으시길 바라겠습니다!
수고하셨습니다~

2019-10-26 06:53 UTC, yk1028 approved these changes
피드백 반영 👍 
공감되는 내용이 많아 재미있게 읽을 수 있었습니다.
모든 일은 자신이 행복하고 즐기는 게 가장 중요한거 같아요. 
행복하게 즐기면서 살아요!
이 글에 쓴 내용처럼 희봉이 꿈꾸는 프로그래머로서 살아가길 응원합니다:)

2019-12-11 08:43 UTC, woowahan-pjs approved these changes
항상 행복하세요! 👍

2019-12-11 08:43 UTC, merged