[레벨 4 - 회고] 쿠기 미션 제출합니다.
woowacourse/woowa-writing-1 pull request #167
Opened 2019-12-18 06:29 UTC by men7627

감사합니다!

2019-12-18 13:43 UTC, kunggom requested changes
잘 읽었습니다. 한 문단을 골라 직접 수정해 보았는데, 다른 문단도 이렇게 수정해 보시면 더욱 좋겠습니다.

2019-12-18 13:43 UTC, kunggom commented on 레벨4.md
> +우테코 오프라인 코딩테스트를 진행하고, 우테코 결과 발표를 앞둔 시기를 떠올려 보았습니다. 그 때, 저는 제대로 된 개발 공부를 하고 싶어서 휴학을 한 상태였습니다. 그리고 저의 그 목표를 실현시켜 줄 최고의 수단이 우테코라고 생각했습니다. 그 만큼 너무 간절했습니다. 그래서 결과 발표를 기다리는 동안에 우테코에 참여할 수 있게만 된다면 더 바라는 것 없
```suggestion
우테코 결과 발표를 앞둔 시기, 저는 제대로 된 개발 공부를 하고 싶어서 휴학했었습니다. 그리고 그 목표를 실현할 최고의 수단이 바로 이곳이라고 생각했습니다. 그만큼 너무 간절해서, 결과 발표를 기다리는 동안에 여기에 참여할 수 있게만 된다면 더 바라는 것 없이 정말 열심히 공부하겠다고 생각했었습니다. 운 좋게 우테코에 참여할 수 있게 되자, 취업 생각은 하지도 않은 채 8개월간 오로지 개발 공부에 몰두하기로 다짐했었습니다.

하지만 우테코를 진행하던 도중에, 우아한형제들이 좋은 회사라는 것과 여기에 지원할 기회가 있다는 것을 알게 되었습니다. 그러자 처음 마음과는 다르게 취업 욕심이 생겼습니다. 우아한형제들에 지원하려면 자기소개서도 작성해야 했고, 면접 준비도 필요했습니다. 그렇게 레벨 3 후반부에는 미션에 제대로 집중하지 못한 채 취업 준비에 몰두했습니다. 처음 해보는 취업 준비라서 많이 힘들었고, 취업 과정이 끝난 지금도 후유증이 남아 있습니다. 모든 것이 다 끝난 것만 같고, 이전과 같은 의욕이 생기지 않습니다. 다시 생각해봐도 이 시기에 미션에 집중하지 못했던 것이 정말 아쉽습니다. 그래서 우테코 전체 과정이 끝나면 제대로 집중하지 못했던 레벨 3 미션은 다시 한번 더 해볼 계획입니다.
```
이 문단이 한 덩어리인 데다 너무 길고 중복되는 표현이 반복되어 리팩토링해봤습니다. 같은 단어, 같은 표현을 반복하지 않는 것만으로도 문장의 완성도가 훨씬 높아집니다.

취업 준비와 미션이 겹친 건 정말 아쉽지요. 저도 취업이 잘 안 되면 남는 시간에 복습이나 좀 해보렵니다.

2019-12-19 00:40 UTC, Laterality approved these changes
8개월 간의 소회군요. 글 잘 읽었어요, 쿠기.

저도 종종 번아웃을 겪는데요. 이때는 다른 일에도 집중이 잘 안돼서 일주일 정도는 그냥 아무 생각 없이 놀기도 해요. 그렇게 쉬고 나면 또 새로 하고싶은 일들이 생각나고, 의욕도 조금씩 돌아오더라고요. 겪지 않을 수는 없는 일이다보니, 극복할 수 있는 나만의 방법을 찾는게 좋은 것 같아요.

아무리 열심히 해도 아쉬움은 항상 남는 것 같아요. 그래서 다음에 더 잘하기 위해 노력하게 되기도 하나봐요. 더 발전한 모습으로 쿠기를 다시 볼 수 있으면 좋겠네요:)

2019-12-19 00:40 UTC, Laterality commented on 레벨4.md
> +우테코 오프라인 코딩테스트를 진행하고, 우테코 결과 발표를 앞둔 시기를 떠올려 보았습니다. 그 때, 저는 제대로 된 개발 공부를 하고 싶어서 휴학을 한 상태였습니다. 그리고 저의 그 목표를 실현시켜 줄 최고의 수단이 우테코라고 생각했습니다. 그 만큼 너무 간절했습니다. 그래서 결과 발표를 기다리는 동안에 우테코에 참여할 수 있게만 된다면 더 바라는 것 없
```suggestion
우테코 오프라인 코딩테스트를 진행하고, 우테코 결과 발표를 앞둔 시기를 떠올려 보았습니다. 그 때, 저는 제대로 된 개발 공부를 하고 싶어서 휴학을 한 상태였습니다. 그리고 저의 그 목표를 실현시켜 줄 최고의 수단이 우테코라고 생각했습니다. 그 만큼 너무 간절했습니다. 그래서 결과 발표를 기다리는 동안에 우테코에 참여할 수 있게만 된다면 더 바라는 것 없이 정말 열심히 공부하겠다고 생각했습니다. 그렇게 운이 좋게 우테코에 참여할 수 있게 되었고, 8개월 간 오로지 개발 공부에 몰두하기로 다짐했습니다. 또한, 취업에 대한 생각은 전혀 가지지도 않았었습니다. 우테코에 참여하는 동안은 공부에만 집중할 생각이었기 때문입니다. 하지만 우테코를 진행하던 와중 우아한 형제들이 좋은 회사라는 것을 알게 되었고, 지원할 수 있는 기회를 가질 수 있다는 것을 알게 되었습니다. 그렇게 저는 처음 마음과는 다르게 취업이라는 욕심을 가지게 되었습니다. 우아한 형제들에게 지원을 하려면, 자기 소개서도 작성해야 했고, 면접 준비도 했어야 했습니다. 그렇게 레벨3의 후반부에서는 미션에 제대로 집중하지 못하고 취업 준비에 몰두하게 되었습니다. 생애 처음해보는 취업 준비어서 많이 힘들었습니다. 그러다보니 취업에 대한 모든 과정이 끝나고 나서도 후유증이 있었던 것 같습니다. 모든 것이 다 끝난 것 같고, 이전과 같은 의욕이 생기지 않았던 것 같습니다. 다시 생각해보아도 이 시기에 우테코 과정에 집중하지 못했던 것이 많이 아쉬운 것 같습니다. 그래서 우테코 전체 과정이 끝나고 나면 제대로 집중하지 못했던 레벨 3 미션들은 다시 한번씩 더 해볼 계획입니다.
```

생애 (生涯)  

[명사]
1. 살아 있는 한평생의 기간.

2019-12-19 00:40 UTC, Laterality commented on 레벨4.md
> +## 크루들과 친하게 지냅시다.
저도 낯을 많이 가리는 편인데, 페어 프로그래밍을 하면서 다른 크루들과 자연스럽게 친해질 수 있어서 좋았어요 :)

2019-12-20 00:09 UTC, yjll1019 approved these changes
안녕하세요~ 쿠기🍪 티버 🐶 입니다!
글을 참 잘 쓰시네요! 잘 읽었습니다 👍 👍 👍 
쿠기는 항상 열심히 하는 모습만 봐서 몰랐는데 레벨3 후 번아웃을 겪으셨군요..ㅠㅠ
8개월 동안 고생하셨습니다!
앞으로 더 발전하는 쿠키가 되길 바라요. 수고하셨습니다~

2019-12-20 00:09 UTC, yjll1019 commented on 레벨4.md
> +저는 낯을 많이 가리는 성격이기도 하고, 사람들에게 먼저 다가가는 것을 잘 못합니다. 그러다보니 우테코 초반에는 페어 이외의 크루들과는 대화를 많이 나눠보지 못했습니다. 또한 공부와 미션의 압박 때문에 크루들과 친해져야겠다는 생각을 못했던 것 같습니다. 하지만 사람들과 쉽게 친해지지 못하는 저도 다른 크루들과 스터디를 하고 팀프로젝트를 하다보니 자연스럽게
저도 여러 크루들과 많은 이야기를 나눠보지 못한 점이 아쉽더라고요..!
그래도 또 친해질 기회가 있지 않을까요?

2019-12-20 10:15 UTC, kunggom approved these changes
좋은 이야기 잘 읽었습니다. 글을 수정하리라 믿고 먼저 Approve하겠습니다.

2019-12-20 10:17 UTC, parker1609 approved these changes
안녕하세요 쿠기!
쿠기가 우아한테크코스를 하면서 느꼈던 생각을 알 수 있어서 좋았습니다. ㅎㅎ 그리고 개발에 집중하기 위해 휴학을 했다는 것이 정말 멋있네요! 저는 쿠기와 우아한테크코스 초기에 페어를 해봐서 대화를 해보았지만, 시간이 지날수록 밝고 재밌는 사람이라는 것을 알 수 있었어요. 8개월 동안 고생 많았습니다! :+1: 
좋은 글 잘 읽었습니다!

2019-12-31 05:00 UTC, merged