[레벨2 - 성장] 닉 미션 제출합니다.
woowacourse/woowa-writing-1 pull request #65
Opened 2019-08-17 11:56 UTC by wbluke

2019-08-19 02:37 UTC, andole87 commented on 2_lose_heart_to_programming.md
> +한 때 피아노라는 악기에 정말 푹 빠져있었다. `~에 푹 빠지다`라는 말을 영어로 `lose heart to [something]` 이라고 쓰기도 한다던데, 표현 그대로 내 전부를 다 걸 정도로 올인했던 20대 초반~중반의 시기가 있었다. 무엇을 하더라도 피아노에 대해 탐구하는 시간이 우선순위 1위를 차지했다. 절실한 마음으로 여러 선생님들께 받았던 피아
관형어에 연결된 명사의 나열이네요. 피아노 레슨, 피아노 컨퍼런스, 화성학 공부, 샤프펜슬, 오선지 노트.
비문에 가까운데요, 이 명사들의 서술부가 있으면 좋겠어요.
ex) ~, ~, ~, ~, 는 나의 전부였다.

2019-08-19 02:44 UTC, andole87 commented on 2_lose_heart_to_programming.md
> +지금은 프로그래밍이라는 또 다른 새로운 세계에 푹 빠져 사느라, 피아노는 실력의 퇴화를 막기 위해 간간히 용을 쓰고 있는 중이지만, 그 당시 보냈던 인고의 시간들은 지금에 와서 오롯이 코딩하는 습관의 토대를 만들어주었다. 덕분에 테크코스 선발 당시 자기소개서 질문 중 하나였던 `마음이 끌리는 무엇인가에 몰입해 일정 수준의 결과물을 만들어 낸 경험이 있나요
`피아노는 실력의 퇴화를 막기 위해 간간히 용을 쓰고 있는 중이지만, 그 당시 보냈던 인고의 시간들은 지금에 와서 오롯이 코딩하는 습관의 토대를 만들어주었다.`
약간 어색하게 느껴집니다. 피아노 실력의 퇴화를 **막고 있는 것**과 코딩하는 습관을 **만들어주는 것**에 연관관계가 없어 보여요.

```suggestion
지금은 프로그래밍이라는 또 다른 새로운 세계에 푹 빠져 살고 있다. 피아노와 분명 다른 분야지만, 그 당시 인고의 시간들은 지금에 와서 오롯이 코딩하는 습관의 토대를 만들어주었다.
```

2019-08-19 02:46 UTC, andole87 commented on 2_lose_heart_to_programming.md
> +"간절함을 그 크기만큼 정직하게 풀어내는 방법은 '치열함'과 '겸손함'이 함께 가야한다는 것을, 몸과 마음으로 기억하게 해준 소중한 경험이었습니다."
`방법은 ~ 가야한다는 것을` 비문 같네요.
```suggestion
"간절함을 그 크기만큼 정직하게 풀어내기 위해서는 '치열함'과 '겸손함'이 함께 가야한다는 것을, 몸과 마음으로 기억하게 해준 소중한 경험이었습니다."  
```

2019-08-19 02:54 UTC, andole87 commented on 2_lose_heart_to_programming.md
> +학과 전공 공부와 피아노 레슨을 동시에 진행하던 시기에는, 사실 지금 생각하면 꽤나 아둔했던 선택이었는데, 욕심만 많았지 어느 쪽에도 확실히 집중하지 못했던 시간들이었다. 매주 있었던 1시간의 레슨에서 꽤나 많은 것들을 새롭게 배우고 이해했음에도, 적용의 영역까지 끌고 가지 않았던 내 가벼운 의지는 휘발성의 단편적인 기억의 조각들을 그리 오래 붙잡고 있지
문학적 표현일 수 있지만, 문장을 정돈하면 더 읽기 좋을 것 같아요. 
```suggestion
학과 전공 공부와 피아노 레슨을 동시에 진행했었다. 지금 생각하면 꽤나 아둔했던 선택이었다. 욕심만 많았지 어느 쪽에도 확실히 집중하지 못했다. 매주 있었던 1시간의 레슨에서 많은 것들을 새롭게 배우고 이해했음에도, 적용의 영역까지 끌고 가지 못했다. 내 가벼운 의지는 휘발성의 단편적인 기억의 조각들을 그리 오래 붙잡고 있지 못했다. 같은 내용의 화성학 이론을 다음주에, 또 그 다음주에 반복해서 배웠다. 수업은 효율적이지 못했고 내 성장은 지지부진했다. 내게는 그저 '무언가 힘내서 배우고 있고, 그래도 이 시간들이 쌓이면 빛을 발할거야'라는 막연한 안도감만 쌓여가고 있었다.  
```

2019-08-19 02:56 UTC, andole87 commented on 2_lose_heart_to_programming.md
> +> 지식의 공유가 일반화되고 상시 접근성이 좋아진 게 좋지만은 않은 이유는 내일도 여전한 자료를 믿고 미루고 또 미루게 된다는 겁니다. 접근하기 좋은 지식을 접할수록 적극적 자세가 요구됩니다. 의자에 엉덩이를 붙이고 허리를 곧게 펴보세요. 노트를 펴고 연필을 쥐어보세요. 진지하게 접근하지 않으면 지식은 모니터에만 머무를 뿐입니다. - 페이스북 페이지 허림
좋은 글이네요. 👏

2019-08-19 03:01 UTC, andole98 requested changes
닉~ 담백한 글 잘 읽었습니다. 역시 잘하는 사람은 이유가 있군요~
글도 굉장히 잘 쓰시네요. 💯 
몇 가지 코멘트 달았습니다. 확인해주세요~

2019-08-19 14:26 UTC, ghost approved these changes
프로젝트 하는 와중에도 정말 잘 쓰셨네요!
코멘트남길 부분이 딱히 없습니다.
읽으면서 든 생각을 몇 군데 남겼는데, 참고만 해주세요~

2019-08-19 14:26 UTC, gch01410 commented on 2_lose_heart_to_programming.md
> +하지만 절대 잊을 것 같지 않았던 내용들은 목표를 달성함과 동시에 점점 흐려져 갔고, 단편적인 기억들을 붙잡으려는 전보다 조금 더 굳건한 의지는 당장 이걸 써먹어야 한다는 위기감을 안겨주었다.
`단편적인 기억들을 붙잡으려는 전보다 조금 더 굳건한 의지는 당장 이걸 써먹어야 한다는 위기감을 안겨주었다.` 
이 부분이 한번에 이해가 안되어서 여러번 읽었습니다..
조금 더 읽기 쉽게 바꾸면 좋을 것 같습니다!

2019-08-19 14:26 UTC, gch01410 commented on 2_lose_heart_to_programming.md
> +그런데 몸이 먼저 반응했다. '전에도 언젠가 이런 고민을 했었던 것 같은데?'
`그런데 몸이 먼저 반응했다. '전에도 언젠가 이런 고민을 했었던 것 같은데?'`
이 문장에 이어서 예전에 고민했었던 내용과 관련된 내용이 나올 것 같았는데, 다음 내용이 연결이 잘 안되는 것 같습니다.

이 문장이 없으면 더 잘 이어지는 느낌이 듭니다.

2019-08-20 00:39 UTC, oeeen approved these changes
안녕하세요! 리뷰어 마틴입니다. 워낙 글을 잘 쓰셔서 리뷰 남길 게 없네요! 💯 
닉이 평소에 일을 대하는 태도에 대해 알게 되었고 역시 이 사람은 멋있는 사람이구나 생각하게 되는 글이네요~
이 글에서 재미있는 공부법들도 배우게 돼서 저도 써먹을 수 있을 것 같아요! 고맙습니다. :)
어휘 자체가 고급스럽고 책을 많이 읽으신 듯한 느낌을 주네요. 문학소년 같은 느낌입니다.
몇 가지 코멘트 남겼으니 참고만 해주세요! approve 하겠습니다.

2019-08-20 00:39 UTC, oeeen commented on 2_lose_heart_to_programming.md
> +한 판 공부법의 핵심은 `스스로 글을 쓰는 공간에 제약을 두는 것` 이다. 정리할 공간이 좁으면, 공부한 내용을 어떻게든 나의 언어로 재정립해서 축약할 수 밖에 없다. 그 과정에서 외부 세계의 떠다니는 지식들이 내면에 자리잡는 스키마로 하나 둘씩 옷을 갈아입는다. 이건 진짜 내 지식이라고 말할 수 있는 순간이 온다.
재미있는 공부법 이네요 :) `스키마로 하나 둘씩 옷을 갈아입는다.` 라는 표현이 예쁘네요 💯

2019-08-20 00:39 UTC, oeeen commented on 2_lose_heart_to_programming.md
> +지금은 프로그래밍이라는 또 다른 새로운 세계에 푹 빠져 사느라, 피아노는 실력의 퇴화를 막기 위해 간간히 용을 쓰고 있는 중이지만, 그 당시 보냈던 인고의 시간들은 지금에 와서 오롯이 코딩하는 습관의 토대를 만들어주었다. 덕분에 테크코스 선발 당시 자기소개서 질문 중 하나였던 `마음이 끌리는 무엇인가에 몰입해 일정 수준의 결과물을 만들어 낸 경험이 있나요
저는 그 질문에 대답하는게 힘들었는데, 닉은 멋진 남자네요 :)

2019-08-20 00:39 UTC, oeeen commented on 2_lose_heart_to_programming.md
> +"간절함을 그 크기만큼 정직하게 풀어내는 방법은 '치열함'과 '겸손함'이 함께 가야한다는 것을, 몸과 마음으로 기억하게 해준 소중한 경험이었습니다."
이 부분은 위에 `마음이 끌리는 무엇인가에 몰입해 일정 수준의~.. ?`의 대답인거죠? 제 이해력이 부족해서 한번에 확 와닿지 않네요.

2019-08-20 00:39 UTC, oeeen commented on 2_lose_heart_to_programming.md
> +테크코스라는 새로운 환경에서 공부하고 생활하다보니, 초반에는 마음에 단 두가지 생각 뿐이 없었다. 그저 주어진 미션을 수행하는 것과, 중요하고 필요하다고 생각하는 공부 주제들을 일단 손에 잡히는대로 공부하는 것. 그러나 점차 공부하는 것 그 자체보다 '공부를 어떻게 하면 더 효과적으로 할 수 있을까?' 라는 질문이 마음 한 구석에 똬리를 틀었다. 욕심은
표현의 차이인 것 같은데 `초반에는 마음에 단 두가지 생각 뿐이었다.` 는 어떨까요? 강조하는 의미에서 `~뿐이 없었다` 라고 할 수도 있겠지만 약간 어색한 표현인 것 같아서요!

2019-08-20 00:39 UTC, oeeen commented on 2_lose_heart_to_programming.md
> +예쁜 걸 (예쁘게 정리하는 걸) 좋아하고 완벽주의가 있는 어떤 이에게는 아주 효과적인 방법이었다.
완벽주의자........

2019-08-20 00:39 UTC, oeeen commented on 2_lose_heart_to_programming.md
> +학과 전공 공부와 피아노 레슨을 동시에 진행하던 시기에는, 사실 지금 생각하면 꽤나 아둔했던 선택이었는데, 욕심만 많았지 어느 쪽에도 확실히 집중하지 못했던 시간들이었다. 매주 있었던 1시간의 레슨에서 꽤나 많은 것들을 새롭게 배우고 이해했음에도, 적용의 영역까지 끌고 가지 않았던 내 가벼운 의지는 휘발성의 단편적인 기억의 조각들을 그리 오래 붙잡고 있지
안돌 말에 동의합니다. 닉의 표현 방식일 수 있고, 실제로 읽어보면 자연스러운 흐름이지만 글로 읽는데에는 약간 불편한 감이 있습니다.

2019-08-20 00:39 UTC, oeeen commented on 2_lose_heart_to_programming.md
> +Lose Heart To Programming!
닉의 태도와 자세를 알 수 있게 되는 좋은 말이네요!

2019-08-20 00:39 UTC, oeeen commented on 2_lose_heart_to_programming.md
> +하지만 절대 잊을 것 같지 않았던 내용들은 목표를 달성함과 동시에 점점 흐려져 갔고, 단편적인 기억들을 붙잡으려는 전보다 조금 더 굳건한 의지는 당장 이걸 써먹어야 한다는 위기감을 안겨주었다.
`단편적인 기억들을 붙잡으려는 전보다 조금 더 굳건한 의지는 당장 이걸 써먹어야 한다는 위기감을 안겨주었다.` 부분이 한번에 이해가 되지 않습니다. +1

2019-08-20 12:00 UTC, wbluke commented on 2_lose_heart_to_programming.md
> +한 때 피아노라는 악기에 정말 푹 빠져있었다. `~에 푹 빠지다`라는 말을 영어로 `lose heart to [something]` 이라고 쓰기도 한다던데, 표현 그대로 내 전부를 다 걸 정도로 올인했던 20대 초반~중반의 시기가 있었다. 무엇을 하더라도 피아노에 대해 탐구하는 시간이 우선순위 1위를 차지했다. 절실한 마음으로 여러 선생님들께 받았던 피아
수정했습니다!

2019-08-20 12:01 UTC, wbluke commented on 2_lose_heart_to_programming.md
> +지금은 프로그래밍이라는 또 다른 새로운 세계에 푹 빠져 사느라, 피아노는 실력의 퇴화를 막기 위해 간간히 용을 쓰고 있는 중이지만, 그 당시 보냈던 인고의 시간들은 지금에 와서 오롯이 코딩하는 습관의 토대를 만들어주었다. 덕분에 테크코스 선발 당시 자기소개서 질문 중 하나였던 `마음이 끌리는 무엇인가에 몰입해 일정 수준의 결과물을 만들어 낸 경험이 있나요
퇴화를 엄청 강조하고 싶었었나봐요...ㅋㅋㅋ 수정했습니다 :)

2019-08-20 12:01 UTC, wbluke commented on 2_lose_heart_to_programming.md
> +"간절함을 그 크기만큼 정직하게 풀어내는 방법은 '치열함'과 '겸손함'이 함께 가야한다는 것을, 몸과 마음으로 기억하게 해준 소중한 경험이었습니다."
괄호로 부연설명을 추가하고, 문장을 조금 더 매끄럽게 만져보았습니다~

2019-08-20 12:02 UTC, wbluke commented on 2_lose_heart_to_programming.md
> +학과 전공 공부와 피아노 레슨을 동시에 진행하던 시기에는, 사실 지금 생각하면 꽤나 아둔했던 선택이었는데, 욕심만 많았지 어느 쪽에도 확실히 집중하지 못했던 시간들이었다. 매주 있었던 1시간의 레슨에서 꽤나 많은 것들을 새롭게 배우고 이해했음에도, 적용의 영역까지 끌고 가지 않았던 내 가벼운 의지는 휘발성의 단편적인 기억의 조각들을 그리 오래 붙잡고 있지
문장의 호흡을 의식적으로 끊으려고 하는데도, 가끔 몰입하다보면 이렇게 긴 문장들이 나오더라구요. 많이 노력해야 할 부분같습니다 ㅎㅎ 수정하였습니다~

2019-08-20 12:03 UTC, wbluke commented on 2_lose_heart_to_programming.md
> +하지만 절대 잊을 것 같지 않았던 내용들은 목표를 달성함과 동시에 점점 흐려져 갔고, 단편적인 기억들을 붙잡으려는 전보다 조금 더 굳건한 의지는 당장 이걸 써먹어야 한다는 위기감을 안겨주었다.
수정하였습니다!

2019-08-20 12:03 UTC, wbluke commented on 2_lose_heart_to_programming.md
> +그런데 몸이 먼저 반응했다. '전에도 언젠가 이런 고민을 했었던 것 같은데?'
글 쓸 때도 많이 고민했던 부분인데, 시원하게 날렸습니다ㅎㅎㅎ

2019-08-20 12:03 UTC, wbluke commented on 2_lose_heart_to_programming.md
> +한 판 공부법의 핵심은 `스스로 글을 쓰는 공간에 제약을 두는 것` 이다. 정리할 공간이 좁으면, 공부한 내용을 어떻게든 나의 언어로 재정립해서 축약할 수 밖에 없다. 그 과정에서 외부 세계의 떠다니는 지식들이 내면에 자리잡는 스키마로 하나 둘씩 옷을 갈아입는다. 이건 진짜 내 지식이라고 말할 수 있는 순간이 온다.
맞아요 예쁘죠 :)

2019-08-20 12:04 UTC, wbluke commented on 2_lose_heart_to_programming.md
> +지금은 프로그래밍이라는 또 다른 새로운 세계에 푹 빠져 사느라, 피아노는 실력의 퇴화를 막기 위해 간간히 용을 쓰고 있는 중이지만, 그 당시 보냈던 인고의 시간들은 지금에 와서 오롯이 코딩하는 습관의 토대를 만들어주었다. 덕분에 테크코스 선발 당시 자기소개서 질문 중 하나였던 `마음이 끌리는 무엇인가에 몰입해 일정 수준의 결과물을 만들어 낸 경험이 있나요
마틴도 멋져요 :)

2019-08-20 12:04 UTC, wbluke commented on 2_lose_heart_to_programming.md
> +테크코스라는 새로운 환경에서 공부하고 생활하다보니, 초반에는 마음에 단 두가지 생각 뿐이 없었다. 그저 주어진 미션을 수행하는 것과, 중요하고 필요하다고 생각하는 공부 주제들을 일단 손에 잡히는대로 공부하는 것. 그러나 점차 공부하는 것 그 자체보다 '공부를 어떻게 하면 더 효과적으로 할 수 있을까?' 라는 질문이 마음 한 구석에 똬리를 틀었다. 욕심은
수정했습니다! 더 알아보기 좋네요 :)

2019-08-20 12:04 UTC, wbluke commented on 2_lose_heart_to_programming.md
> +예쁜 걸 (예쁘게 정리하는 걸) 좋아하고 완벽주의가 있는 어떤 이에게는 아주 효과적인 방법이었다.
= 피곤하게 산다.....

2019-08-20 12:05 UTC, wbluke commented on 2_lose_heart_to_programming.md
> +Lose Heart To Programming!
열심열심

2019-08-20 12:05 UTC, wbluke commented on 2_lose_heart_to_programming.md
> +하지만 절대 잊을 것 같지 않았던 내용들은 목표를 달성함과 동시에 점점 흐려져 갔고, 단편적인 기억들을 붙잡으려는 전보다 조금 더 굳건한 의지는 당장 이걸 써먹어야 한다는 위기감을 안겨주었다.
수정하였습니다~

2019-08-20 15:57 UTC, heebong commented on 2_lose_heart_to_programming.md
> +
👍 자신의 이야기 + 두 가지의 공통점으로 시작하는 도입부 좋아요!

2019-08-20 16:00 UTC, heebong approved these changes
안녕하세요 닉! 희봉입니다 😄 
글 너무 잘 읽었습니다 👏 
특히 글의 구성을 잘 짠거같아요. 피아노와 프로그래밍의 공통점을 이야기한 도입부를 시작으로 자신이 터득하게된 공부법들, 그리고 인용 글로 마무리! 발표도 짜임새있게 잘하시는데 글도 구성이 좋았습니다. 역시 발표신... 👍  특히 닉의 생각이 많이 드러나서 같이 대화를 나눈 기분이에요. 

Lose Heart To Programming! 함께 열심히 달려봅시다!

2019-08-20 16:03 UTC, heebong commented on 2_lose_heart_to_programming.md
> +"(피아노를 깊게 공부했던 경험은) 간절함을 그 크기만큼 정직하게 풀어내기 위해서 '치열함'과 '겸손함'이 함께 가야한다라는 것을, 몸과 마음으로 기억하게 해주었습니다."
`'치열함'과 '겸손함'이 함께 가야한다`는 말이 좋네요! 많이 생각하게 만듭니다

2019-08-20 16:04 UTC, heebong commented on 2_lose_heart_to_programming.md
> +한 때 학과 전공 공부와 피아노 레슨을 동시에 진행하던 시기가 있었다. 사실 지금 생각하면 꽤나 아둔했던 선택이었는데, 욕심만 많았지 어느 쪽에도 확실히 집중하지 못했던 시간들이었다. 매주 있었던 1시간의 레슨에서 꽤나 많은 것들을 새롭게 배우고 이해했음에도, 내 가벼운 의지는 얻은 지식들을 적용의 영역까지 끌고 가지 못했다. 그렇게 휘발성의 단편적인 기
많이 공감가는 내용입니다. 휘발되는 기억의 조각들...

2019-08-20 16:07 UTC, heebong commented on 2_lose_heart_to_programming.md
> +위기감은 곧 누가 시키지도 않은 일을 하게 만들었다. 스터디에서 사용할 책에 수록되어 있는 예제 프로젝트 코드를, 배운 지식들을 적용하여 새롭게 처음부터 다시 만들었다. 더 나아가 해당 지식에 연장선에 있는 라이브러리까지 공부하면서 적용해나갔다. 배움에서 적용까지 이르는 시간을 최대한 `빠른 사이클` 로 가져간 경험이었다. 강의로만 지식을 습득할 때와는
공감갑니다. 빠르게 적용시켜 익히는게 중요한거같아요!

2019-08-20 16:07 UTC, heebong commented on 2_lose_heart_to_programming.md
> +Lose Heart To Programming!
👍 👍

2019-08-22 00:54 UTC, andole98 approved these changes
수정하신 것 살펴봤습니다 👍 
재능이 참 많으시네요. 피아노에 코딩에 글쓰기도 매우 잘하시는군요 💯 엄친아포스..
고생 많으셨습니다.

2019-08-22 01:53 UTC, wbluke commented on 2_lose_heart_to_programming.md
> +한 때 학과 전공 공부와 피아노 레슨을 동시에 진행하던 시기가 있었다. 사실 지금 생각하면 꽤나 아둔했던 선택이었는데, 욕심만 많았지 어느 쪽에도 확실히 집중하지 못했던 시간들이었다. 매주 있었던 1시간의 레슨에서 꽤나 많은 것들을 새롭게 배우고 이해했음에도, 내 가벼운 의지는 얻은 지식들을 적용의 영역까지 끌고 가지 못했다. 그렇게 휘발성의 단편적인 기
흑흑 영속성 보장되었으면 좋겠다.......

2019-09-11 02:18 UTC, merged